require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/test/**/*'

Metrics/MethodLength:
  Exclude:
    - '**/test/**/*'
